'use strict';
const $=id=>document.getElementById(id);
const state={step:0,catalog:[],brand:'',channel:'',category:'',selected:null,values:{},signature:''};
const labels=['Cliente','Progetto','Canale','Servizio','Messaggio','Bozza'];
const phase={primo:'Primo contatto',secondo:'Dopo incontro / contatto',terzo:'Promemoria',servizi:'Servizi e comunicazioni'};
const placeholders=text=>[...new Set([...text.matchAll(/\[([^\]\n]+)\]/g)].map(m=>m[1]))];
function matching(){return state.catalog.filter(t=>t.brand===state.brand&&(t.channel===state.channel||t.channel==='entrambi'));}
function choice(parent,group,value,title,detail,selected,onChange){const label=document.createElement('label');label.className='choice';const radio=document.createElement('input');radio.type='radio';radio.name=group;radio.value=value;radio.checked=selected;radio.onchange=()=>{onChange(value);$('error').textContent='';};const text=document.createElement('span');const strong=document.createElement('strong');strong.textContent=title;text.append(strong);if(detail){const small=document.createElement('small');small.textContent=detail;text.append(small);}label.append(radio,text);parent.append(label);}
function services(){const parent=$('services');parent.replaceChildren();const categories=[...new Set(matching().map(t=>t.category))].sort((a,b)=>a.localeCompare(b,'it'));categories.forEach(c=>choice(parent,'service',c,c,`${matching().filter(t=>t.category===c).length} messaggi`,state.category===c,value=>{if(state.category!==value){state.category=value;state.selected=null;state.signature='';$('stage').value='tutti';}}));}
function messagePreview(text){const compact=substitute(text).replace(/\s+/g,' ').trim();return compact.length>220?compact.slice(0,220).trimEnd()+'…':compact;}
function templates(){const parent=$('templates');parent.replaceChildren();const items=matching().filter(t=>t.category===state.category&&($('stage').value==='tutti'||t.stage===$('stage').value));if(!items.some(t=>t.id===state.selected?.id))state.selected=null;items.forEach(t=>choice(parent,'template',t.id,t.sourceLabel,messagePreview(t.body),state.selected?.id===t.id,id=>{state.selected=items.find(x=>x.id===id);}));$('empty').hidden=items.length>0;}
function showStep(){document.querySelectorAll('[data-step]').forEach(p=>p.hidden=Number(p.dataset.step)!==state.step);document.querySelectorAll('#progress li').forEach((li,i)=>{li.classList.toggle('active',i===state.step);li.classList.toggle('done',i<state.step);if(i===state.step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});$('step-counter').textContent=`PASSAGGIO ${state.step+1} DI 6 · ${labels[state.step].toUpperCase()}`;$('back').hidden=state.step===0;$('next').hidden=state.step===5;$('new-message').hidden=state.step!==5;$('next').textContent=state.step===4?'Genera la bozza':'Continua';$('error').textContent='';$('trail').textContent=[state.values.Nome,state.brand,state.channel==='email'?'Email':state.channel==='whatsapp'?'WhatsApp':'',state.category].filter(Boolean).join(' / ');if(state.step===3)services();if(state.step===4)templates();if(state.step===5)prepareDraft();const heading=document.querySelector(`[data-step="${state.step}"] h2`);heading.focus();}
function validate(){if(state.step===0){if(!$('client-name').value.trim()){ $('client-name').focus();return 'Inserisci il nome del cliente per continuare.';}if(!$('client-email').checkValidity()){ $('client-email').focus();return 'Controlla l’indirizzo email inserito.';}const name=$('client-name').value.trim();state.values.Nome=name;state.values.cliente=name;state.values.Azienda=$('company').value.trim();}if(state.step===1&&!state.brand)return 'Scegli Sitointerattivo oppure Abracadabra.';if(state.step===2&&!state.channel)return 'Scegli email oppure WhatsApp.';if(state.step===3&&!state.category)return 'Seleziona un servizio.';if(state.step===4&&!state.selected)return 'Seleziona un messaggio disponibile per creare la bozza.';return '';}
function substitute(text){return text.replace(/\[([^\]\n]+)\]/g,(all,key)=>state.values[key]?.trim()||all);}
function compose(){if(!state.selected)return;$('subject').value=substitute(state.selected.subject);$('message').value=substitute(state.selected.body);state.signature=JSON.stringify([state.selected.id,state.values,state.channel]);$('feedback').textContent='';warnings();}
function prepareDraft(){const t=state.selected;const summary=$('summary');summary.replaceChildren();[state.values.Nome,state.brand,state.channel==='email'?'Email':'WhatsApp',state.category,t.sourceLabel].forEach(value=>{const span=document.createElement('span');span.textContent=value;summary.append(span);});const recipient=state.channel==='email'?$('client-email').value.trim():$('client-phone').value.trim();$('recipient').textContent=recipient?`Destinatario: ${recipient}`:'Destinatario: da inserire nel tuo programma email o in WhatsApp.';$('subject').hidden=$('subject-label').hidden=state.channel!=='email';const keys=placeholders(t.body+(state.channel==='email'?t.subject:''));const extras=keys.filter(key=>!['Nome','cliente'].includes(key)&&(key!=='Azienda'||!state.values.Azienda));$('fields').replaceChildren();$('extra-section').hidden=extras.length===0;extras.forEach((key,i)=>{const wrap=document.createElement('div');const label=document.createElement('label');label.htmlFor=`field-${i}`;label.textContent=key;const input=document.createElement('input');input.id=`field-${i}`;input.value=state.values[key]||'';input.placeholder=`Inserisci ${key.toLowerCase()}`;if(/password/i.test(key))input.type='password';input.oninput=()=>{state.values[key]=input.value;compose();};wrap.append(label,input);$('fields').append(wrap);});if(state.signature!==JSON.stringify([t.id,state.values,state.channel]))compose();else warnings();}
function warnings(){const missing=placeholders($('message').value+(state.channel==='email'?$('subject').value:''));const notes=[];if(missing.length)notes.push(`Da completare: ${missing.join(', ')}.`);if(state.channel==='email'&&!$('subject').value.trim())notes.push('Aggiungi un oggetto email.');if(/alleg|presentazione promessa/i.test($('message').value))notes.push('Aggiungi manualmente gli allegati citati.');if(/C:\\|DA FARE|FINIRE|\b202[0-6]\b/i.test($('message').value))notes.push('Verifica date, percorsi locali e note prima di usare il testo.');$('warning').textContent=notes.join(' ');}
function output(){return(state.channel==='email'&&$('subject').value.trim()?`Oggetto: ${$('subject').value}\n\n`:'')+$('message').value;}
$('next').onclick=()=>{const error=validate();if(error){$('error').textContent=error;return;}state.step++;showStep();};$('back').onclick=()=>{state.step--;showStep();};$('stage').onchange=templates;['message','subject'].forEach(id=>$(id).oninput=warnings);$('reset-draft').onclick=compose;
$('new-message').onclick=()=>{state.step=0;state.brand=state.channel=state.category='';state.selected=null;state.values={};state.signature='';['client-name','company','client-email','client-phone'].forEach(id=>$(id).value='');$('stage').value='tutti';document.querySelectorAll('input[type="radio"]').forEach(r=>r.checked=false);showStep();};
$('copy').onclick=async()=>{const text=output();let copied=false;try{await navigator.clipboard.writeText(text);copied=true;}catch{const helper=document.createElement('textarea');helper.value=text;helper.style.cssText='position:fixed;left:-9999px';document.body.append(helper);helper.select();try{copied=document.execCommand('copy');}catch{}helper.remove();}if(copied)$('feedback').textContent='Bozza copiata. Incollala nella tua email o in WhatsApp.';else{$('message').focus();$('message').select();$('feedback').textContent='Usa Ctrl+C / ⌘C per copiare il testo selezionato. Copia l’oggetto separatamente.';}};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([output()],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${state.brand}-${state.channel}-bozza.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('feedback').textContent='Bozza scaricata.';};
function loadCatalog(data){state.catalog=data;choice($('brands'),'brand','Sitointerattivo','Sitointerattivo','Marketing, eventi e learning',false,value=>{if(value!==state.brand){state.brand=value;state.category='';state.selected=null;state.signature='';}});choice($('brands'),'brand','Abracadabra','Abracadabra','Magia, spettacoli ed esperienze',false,value=>{if(value!==state.brand){state.brand=value;state.category='';state.selected=null;state.signature='';}});choice($('channels'),'channel','email','Email','Bozza con oggetto e testo',false,value=>{if(value!==state.channel){state.channel=value;state.category='';state.selected=null;state.signature='';}});choice($('channels'),'channel','whatsapp','WhatsApp','Messaggio pronto da copiare',false,value=>{if(value!==state.channel){state.channel=value;state.category='';state.selected=null;state.signature='';}});$('next').disabled=false;showStep();}
const embedded=$('embedded-catalog');if(embedded)loadCatalog(JSON.parse(embedded.textContent));else fetch('catalog.json').then(r=>{if(!r.ok)throw new Error();return r.json();}).then(loadCatalog).catch(()=>{$('error').textContent='Impossibile caricare i messaggi. Apri il file Contatto.html.';});
