// Eseguire con Playwright disponibile nel percorso moduli Node.
const {chromium}=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({acceptDownloads:true});
 await context.setOffline(true);
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setContent(fs.readFileSync(path.join(__dirname,'../Contatto.html'),'utf8'));
 const next=()=>page.getByRole('button',{name:'Continua',exact:true}).click();
 const visible=async step=>{assert.equal(await page.locator('[data-step]:visible').count(),1);assert.ok(await page.locator(`[data-step="${step}"]`).isVisible());};
 await visible(0);await next();assert.ok((await page.locator('#error').textContent()).includes('nome'));
 await page.getByLabel('Nome del cliente').fill('Giulia');await page.getByLabel('Nome azienda').fill('Studio Aurora');
 await next();await visible(1);await next();assert.ok((await page.locator('#error').textContent()).includes('Scegli'));
 await page.getByRole('radio',{name:'Abracadabra',exact:false}).check();await next();await visible(2);
 await page.getByRole('radio',{name:'WhatsApp',exact:false}).check();await next();await visible(3);
 assert.equal(await page.getByRole('radio',{name:'Servizi informatica',exact:false}).count(),0);
 await page.getByRole('radio',{name:'Presentazione post telefonata/contatto',exact:false}).check();await next();await visible(4);
 await page.locator('#stage').selectOption('terzo');assert.ok(await page.locator('#empty').isVisible());await page.getByRole('button',{name:'Genera la bozza'}).click();await visible(4);
 await page.locator('#stage').selectOption('tutti');await page.getByRole('radio',{name:'Testo invio presentazione',exact:false}).check();
 await page.getByRole('button',{name:'Genera la bozza'}).click();await visible(5);
 assert.ok((await page.locator('#message').inputValue()).includes('Giulia ciao'));
 assert.ok(!(await page.locator('#message').inputValue()).includes('[Nome]'));
 assert.equal(await page.locator('#subject').isVisible(),false);
 assert.ok((await page.locator('#summary').textContent()).includes('Abracadabra'));
 await page.locator('#message').fill('Bozza modificata da Giulia');await page.getByRole('button',{name:'Indietro',exact:true}).click();await visible(4);
 await page.getByRole('button',{name:'Genera la bozza'}).click();assert.equal(await page.locator('#message').inputValue(),'Bozza modificata da Giulia');
 await page.getByRole('button',{name:'Copia bozza',exact:true}).click();assert.ok((await page.locator('#feedback').textContent()).includes('copiata'));
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Scarica .txt'}).click();assert.ok((await download).suggestedFilename().includes('whatsapp'));
 await page.getByRole('button',{name:'Nuovo messaggio',exact:true}).click();await visible(0);assert.equal(await page.locator('#client-name').inputValue(),'');
 await page.getByLabel('Nome del cliente').fill('Marco');await page.getByLabel('Nome azienda').fill('Alfa');await next();await page.getByRole('radio',{name:'Sitointerattivo',exact:false}).check();await next();await page.getByRole('radio',{name:'Email',exact:false}).check();await next();await page.getByRole('radio',{name:'Presentazione aziendale',exact:false}).check();await next();await page.getByRole('radio',{name:'Testo mail intero',exact:false}).check();await page.getByRole('button',{name:'Genera la bozza'}).click();
 assert.ok((await page.locator('#message').inputValue()).includes('Gentile Marco'));
 assert.ok((await page.locator('#message').inputValue()).includes('Alfa'));
 await page.getByLabel('Servizio',{exact:true}).fill('sito web');await page.getByLabel('Descrizione Servizio',{exact:true}).fill('presentare i prodotti');
 assert.ok(!(await page.locator('#warning').textContent()).includes('Da completare'));
 assert.ok(await page.locator('#subject').isVisible());
 await page.screenshot({path:'/workspace/Contatto-bozza.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.getByRole('button',{name:'Nuovo messaggio',exact:true}).click();await page.screenshot({path:'/workspace/Contatto-percorso.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: percorso completo WhatsApp ed email, schermata singola, validazione, isolamento progetti, modelli Word, bozza, personalizzazione, copia, download, modifiche conservate, reset, mobile e offline.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
